import { IconInfo } from '../shared';

export const iconInfo: IconInfo = {
  icons: {
    arrowUpDown: 'icons/exampletheme/arrow-up-down.svg',
    error: 'icons/exampletheme/error-circle.svg',
    phoneLandline: 'icons/exampletheme/phone-landline.svg',
    accessibility: 'icons/exampletheme/accessibility.svg',
    minus: 'icons/exampletheme/minus.svg',
    arrowLast: 'icons/exampletheme/arrow-last.svg',
    menu: 'icons/exampletheme/menu.svg',
    geolocation: 'icons/exampletheme/geolocation.svg',
    upload: 'icons/exampletheme/upload.svg',
    calendarNew: 'icons/exampletheme/calendar-new.svg',
    cancelClose: 'icons/exampletheme/cancel-close.svg',
    arrowLeft: 'icons/exampletheme/arrow-left.svg',
    calendar: 'icons/exampletheme/calendar.svg',
    comment: 'icons/exampletheme/comment.svg',
    arrowUp: 'icons/exampletheme/arrow-up.svg',
    delete: 'icons/exampletheme/delete.svg',
    edit: 'icons/exampletheme/edit.svg',
    more: 'icons/exampletheme/more.svg',
    arrowBottom: 'icons/exampletheme/arrow-bottom.svg',
    openNewWindow: 'icons/exampletheme/open-new-window.svg',
    moreAndroid: 'icons/exampletheme/more-android.svg',
    notification: 'icons/exampletheme/notification.svg',
    zoomOut: 'icons/exampletheme/zoom-out.svg',
    message: 'icons/exampletheme/message.svg',
    thumbDown: 'icons/exampletheme/thumb-down.svg',
    zoomIn: 'icons/exampletheme/zoom-in.svg',
    mic: 'icons/exampletheme/mic.svg',
    infoCircle: 'icons/exampletheme/info-circle.svg',
    check: 'icons/exampletheme/check.svg',
    plus: 'icons/exampletheme/plus.svg',
    arrowTop: 'icons/exampletheme/arrow-top.svg',
    awardWinning: 'icons/exampletheme/award-winning.svg',
    phoneMobile: 'icons/exampletheme/phone-mobile.svg',
    time: 'icons/exampletheme/time.svg',
    download: 'icons/exampletheme/download.svg',
    settings: 'icons/exampletheme/settings.svg',
    arrowRight: 'icons/exampletheme/arrow-right.svg',
    arrowFirst: 'icons/exampletheme/arrow-first.svg',
    favouritesFilled: 'icons/exampletheme/favourites-filled.svg',
    list: 'icons/exampletheme/list.svg',
    favouritesOutlined: 'icons/exampletheme/favourites-outlined.svg',
    locationPin: 'icons/exampletheme/location-pin.svg',
    home: 'icons/exampletheme/home.svg',
    viewList: 'icons/exampletheme/view-list.svg',
    account: 'icons/exampletheme/account.svg',
    viewGrid: 'icons/exampletheme/view-grid.svg',
    thumbUp: 'icons/exampletheme/thumb-up.svg',
    locked: 'icons/exampletheme/locked.svg',
    arrowDown: 'icons/exampletheme/arrow-down.svg',
    search: 'icons/exampletheme/search.svg',
  }
};
